### ISSUE TITLE
The installation steps are not available...

### ISSUE THREAD

**Issue by mkjmkumar** [zlataovce/mind#1]
I just want to check if this project is active so that I can provide help in order to make this project more presentable. I am new to GoLang but had done lot of simple projects in Go. I can help you with developing some stuff...

**Comment by zlataovce** [comment]
this project is more of a minimal working prototype, because I was in need of a mind mapping software at the time. not intending to maintain the repository, the code is terrible; I published it just because someone may have a similar need.

run `go build -v -ldflags="-s -w" -o mind` to produce a binary or just `go run mind.go`, if you want to use it.

**Comment by mkjmkumar** [comment]
Thanks for your response!!
Windows and Ubuntu both were showing the gcc errors therefore the below steps helped me to run it successfully.
Error:-exec: "gcc": executable file not found in %PATH% when trying go build
To solve it run on PowerShell below: 
`>choco install mingw -y`
`>refreshenv`
To Solve it on Ubuntu run below:
`$apt-get install build-essential`

Also, I have noticed that if the size of the container is small say (512mb and 1Core) gcc would stuck and not respond, to solve it sometimes we need to increase the size of the container. 
 
Also the execution from command prompt required for store.go as well therefore I have used `go run .`
